name: "yt-dlp WebUI"
description: "A simple web interface for yt-dlp"
version: "1.0.22"
slug: "yt-dlp-webui"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
ingress: true
ingress_port: 3000
panel: true
panel_icon: "mdi:download"
map:
  - share:rw
  - media:rw
options:
  yt_dlp_path: "yt-dlp"
  history_path: "/data/history.json"
  allowed_locations:
    - name: "Downloads"
      path: "/share/downloads"
  extra_args: ""
  auto_update: true
schema:
  yt_dlp_path: str
  history_path: str
  allowed_locations:
    - name: str
      path: str
  extra_args: str
  auto_update: bool
