name: "yt-dlp WebUI"
description: "A simple web interface for yt-dlp"
version: "1.0.0"
slug: "yt_dlp_webui"
boot: auto
startup: application
panel: true
map:
  - share:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
init: false
options:
  yt_dlp_path: "yt-dlp"
  history_path: "/data/history.json"
  allowed_locations:
    - name: "Downloads"
      path: "/share/downloads"
  extra_args: []
  auto_update: true
schema:
  yt_dlp_path: string
  history_path: string
  allowed_locations:
    - name: string
      path: string
  extra_args:
    - string
  auto_update: boolean
ingress: true
ingress_port: 5173
panel_icon: "mdi:download"
